[versions]
agp = "9.0.0"
kotlin = "2.3.10"

about-libraries = "14.0.0-b02"
androidx-activity = "1.12.4"
androidx-collection = "1.5.0"
androidx-navigation3 = "1.1.0-alpha04"
kyant-shapes = "1.1.0"
jetbrains-androidx-navigationevent = "1.0.1"
jetbrains-compose-multiplatform = "1.10.1"
jetbrains-compose-window-size = "1.9.0"
jetbrains-dokka = "2.2.0-Beta"
jetbrains-compose-hotReload = "1.0.0"
jetbrains-lifecycle = "2.10.0-alpha08"
materialKolor-utilities = "4.1.1"
spotless = "8.2.1"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
jetbrains-androidx-navigationevent = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "jetbrains-androidx-navigationevent" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose-multiplatform" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose-multiplatform" }
jetbrains-compose-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetbrains-compose-window-size" }
jetbrains-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
kyant-shapes = { module = "io.github.kyant0:shapes", version.ref = "kyant-shapes" }
materialKolor-utilities = { module = "com.materialkolor:material-color-utilities", version.ref = "materialKolor-utilities" }

[plugins]
androidApplication = { id = "com.android.application" } # AGP
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library" } # AGP
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform" } # KGP

aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "jetbrains-compose-hotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose-multiplatform" }
dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }