[versions]
android-gradle-plugin = "8.13.2"
androidx-activity = "1.12.2"
androidx-collection = "1.5.0"
androidx-navigation3 = "1.1.0-alpha02"
gaze-capsule = "2.1.1-patch2"
jetbrains-androidx-navigationevent = "1.0.0"
jetbrains-compose-multiplatform = "1.10.0"
jetbrains-compose-window-size = "1.9.0"
jetbrains-dokka = "2.1.0"
jetbrains-lifecycle = "2.10.0-alpha07"
kotlin = "2.2.21"
material-kolor = "4.0.5"
spotless = "8.1.0"

[libraries]
# Libraries
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "androidx-collection" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "androidx-navigation3" }
jetbrains-androidx-navigationevent = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "jetbrains-androidx-navigationevent" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose-multiplatform" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose-multiplatform" }
jetbrains-compose-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetbrains-compose-window-size" }
jetbrains-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
gaze-capsule = { module = "com.mocharealm.gaze:capsule", version.ref = "gaze-capsule" }
materialKolor-utilities = { module = "com.materialkolor:material-color-utilities", version.ref = "material-kolor" }

# Gradle Plugins
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-library-gradle-plugin = { module = "com.android.kotlin.multiplatform.library:com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "android-gradle-plugin" }
android-application-gradle-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jetbrains-compose-multiplatform" }
kotlin-compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
spotless-plugin-gradle = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
